import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Segmented, Table, Tag } from 'antd';
import { ArrowRightOutlined, ArrowUpOutlined, CalendarOutlined, DollarOutlined, FileTextOutlined, TeamOutlined, RiseOutlined, PlusOutlined, ThunderboltOutlined, WarningOutlined } from '@ant-design/icons';
import { useStore } from '../store';
import { metrics, money, outstanding, total, trend, periodStart, today } from '../lib/business';
import { Chart, chartColors, axisStyle } from '../components/Chart';
import { PageHeading, MetricCard, Panel } from '../components/Shared';
import type { Period, Order } from '../types';
export const statusColors: Record<string,string>={'待确认':'gold','进行中':'blue','已完成':'green','已取消':'default','重点客户':'blue','普通客户':'cyan','潜在客户':'orange'};
export const periodOptions=[{label:'本周',value:'week'},{label:'本月',value:'month'},{label:'今年',value:'year'}];
export default function Dashboard() {
  const {data}=useStore(); const navigate=useNavigate(); const [period,setPeriod]=useState<Period>('month'); const m=metrics(data,period); const t=trend(data,period);
  const allCustomers=data.customers.length;const unpaid=data.orders.filter(o=>outstanding(o)>0);
  const income=Object.entries(m.entries.filter(t=>t.type==='收入').reduce<Record<string,number>>((acc,t)=>({...acc,[t.category]:(acc[t.category]||0)+t.amount}),{})).map(([name,value])=>({name,value}));
  const currentOrders=data.orders.filter(o=>o.date>=periodStart(period)&&o.date<=today());
  return <div className="page-enter"><PageHeading title="经营概览" description="每一份努力，都有迹可循。掌握生意的每一个关键变化。" extra={<><span className="date-pill"><CalendarOutlined/> {new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}</span><Button type="primary" icon={<PlusOutlined/>} onClick={()=>navigate('/orders?new=1')}>新建订单</Button></>}/>
    <div className="overview-intro"><div><span className="live-dot"/> 你的经营，一目了然 <span className="muted intro-note">数据随业务记录实时更新</span></div><Segmented value={period} options={periodOptions} onChange={v=>setPeriod(v as Period)}/></div>
    <div className="metrics-grid"><MetricCard title="营业收入" value={money(m.revenue)} icon={<DollarOutlined/>} foot="已收回款 + 其他收入" hint="采用收付实现口径，订单回款按订单日期统计，不含未收款。"/><MetricCard title="订单总数" value={m.orders} icon={<FileTextOutlined/>} foot={`${currentOrders.filter(o=>o.status==='已完成').length} 笔已完成 · 不含取消订单`} tone="teal"/><MetricCard title="净利润" value={money(m.profit)} icon={<RiseOutlined/>} foot={`经营支出 ${money(m.expense)}`} hint="演示口径为收入减支出，不代表正式会计报表利润。" tone="purple"/><MetricCard title="客户总数" value={allCustomers} icon={<TeamOutlined/>} foot={`所选期间新增 ${m.customers} 位客户`} tone="amber"/></div>
    <div className="dashboard-charts"><Panel title="经营趋势" subtitle={period==='week'?'本周每日收入与支出':period==='month'?'本月每日收入与支出':'今年每月收入与支出'} extra={<span className="subtle-label">单位：元</span>}><Chart label="收入和支出趋势折线图" height={282} option={{color:chartColors,tooltip:{trigger:'axis'},legend:{top:8,right:0,itemWidth:12,itemHeight:8,icon:'roundRect',textStyle:{color:'#708099'}},grid:{left:8,right:15,bottom:8,top:52,containLabel:true},xAxis:{...axisStyle,type:'category',boundaryGap:false,data:t.map(x=>x.label)},yAxis:{...axisStyle,type:'value'},series:[{name:'营业收入',type:'line',smooth:true,symbol:'circle',symbolSize:5,data:t.map(x=>x.revenue),lineStyle:{width:3},areaStyle:{color:{type:'linear',x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:'#3475f42d'},{offset:1,color:'#3475f400'}]}}},{name:'经营支出',type:'line',smooth:true,symbol:'circle',symbolSize:4,data:t.map(x=>x.expense),lineStyle:{width:2,type:'dashed'}}]}}/></Panel>
    <Panel title="收入结构" subtitle="了解你的业务增长来源" extra={<Tag className="soft-tag">已收收入</Tag>}><div className="donut-wrap"><Chart label="按业务分类的收入结构环形图" height={208} option={{color:chartColors,tooltip:{trigger:'item',formatter:'{b}<br/>¥{c}（{d}%）'},series:[{type:'pie',radius:['62%','82%'],center:['50%','50%'],label:{show:false},itemStyle:{borderColor:'#fff',borderWidth:4,borderRadius:6},data:income.length?income:[{name:'暂无收入',value:1,itemStyle:{color:'#edf1f7'}}]}]}}/><div className="donut-center"><span>收入来源</span><strong>{income.length}<small> 类</small></strong></div></div><div className="income-legend">{income.map((x,i)=><div key={x.name}><span><i style={{background:chartColors[i%chartColors.length]}}/>{x.name}</span><strong>{m.revenue?(x.value/m.revenue*100).toFixed(1):0}%</strong></div>)}</div></Panel></div>
    <div className="dashboard-bottom"><Panel title="最近订单" subtitle="项目进展与客户动态，尽在掌握" extra={<Button type="link" onClick={()=>navigate('/orders')}>查看全部 <ArrowRightOutlined/></Button>}><Table<Order> className="recent-table" rowKey="id" size="middle" pagination={false} scroll={{x:590}} dataSource={[...data.orders].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5)} columns={[{title:'订单 / 客户',key:'title',render:(_,o)=><div><span className="table-primary">{o.title}</span><span className="table-secondary">{data.customers.find(c=>c.id===o.customerId)?.name}</span></div>},{title:'订单金额',dataIndex:'amount',render:money},{title:'状态',dataIndex:'status',render:v=><Tag color={statusColors[v]}>{v}</Tag>},{title:'日期',dataIndex:'date',render:v=><span className="muted">{v.slice(5)}</span>} ]}/></Panel>
    <div className="insights-column"><section className="ai-insight"><div className="ai-insight-title"><span className="ai-icon"><ThunderboltOutlined/></span><h2>AI 经营洞察</h2><Tag>智能助手</Tag></div><p>把数据看懂，把下一步想清楚。</p><div className="insight-copy">你有 <strong>{unpaid.length} 笔</strong>订单待回款，共 <strong>{money(total(unpaid.map(outstanding)))}</strong>。及时跟进回款，让现金流更从容。</div><Button block onClick={()=>navigate('/assistant?q=经营情况总结')}>查看完整经营分析 <ArrowRightOutlined/></Button></section>
    <section className="todo-panel"><div className="todo-title"><h2>经营待办</h2><span>{unpaid.length+m.lowStock.length} 项待关注</span></div><button onClick={()=>navigate('/orders?filter=unpaid')}><span className="todo-icon blue"><FileTextOutlined/></span><span><strong>跟进订单回款</strong><small>{unpaid.length} 笔订单尚未结清</small></span><ArrowRightOutlined/></button><button onClick={()=>navigate('/inventory?filter=low')}><span className="todo-icon orange"><WarningOutlined/></span><span><strong>留意库存预警</strong><small>{m.lowStock.length} 项商品低于安全库存</small></span><ArrowRightOutlined/></button></section></div></div>
    <Panel title="订单状态" className="status-panel" extra={<span className="subtle-label">所选期间 · 包含已取消</span>}><div className="order-status-row">{['待确认','进行中','已完成','已取消'].map((s,i)=><div key={s}><span className={`status-marker s${i}`}/><span>{s}</span><strong>{currentOrders.filter(o=>o.status===s).length}</strong><span className="status-track"><i style={{width:`${currentOrders.length?currentOrders.filter(o=>o.status===s).length/currentOrders.length*100:0}%`,background:chartColors[i]}}/></span></div>)}</div></Panel>
    <div className="page-footer"><span>云迹科技 · 让小生意，也有大视野</span><span><ArrowUpOutlined/> 每一次记录，都是经营的进步</span></div>
  </div>;
}
