import { useState } from 'react';
import { Button, Form, Input, App as AntApp } from 'antd';
import { ArrowRightOutlined, LockOutlined, UserOutlined, CheckOutlined, RiseOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
export default function Login({onLogin}:{onLogin:()=>void}) {
  const {message}=AntApp.useApp();const navigate=useNavigate();const [loading,setLoading]=useState(false);
  const login=()=>{setLoading(true);try{localStorage.setItem('yunji-session','demo');onLogin();navigate('/');}catch{message.error('浏览器禁止本地存储，请允许存储后重试。');}finally{setLoading(false);}};
  return <main className="login-page"><section className="login-story"><a className="brand" href="#/login"><img src="/favicon.svg" alt=""/><span>云迹科技<small>YUNJI TECHNOLOGY</small></span></a><div className="login-story-main"><span className="login-eyebrow">为每一个认真经营的人</span><h1>小团队，<br/>也有<span>大视野。</span></h1><p>从第一位客户，到下一次增长。<br/>让经营井然有序，让决策有迹可循。</p><div className="login-visual"><div><span>经营的每一步，都在向上</span><RiseOutlined/></div><div className="visual-bars">{[26,42,35,58,47,69,63,82,76,95].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="visual-bottom"><span>记录</span><span>洞察</span><span>成长</span></div></div><div className="login-benefits"><span><CheckOutlined/> 经营数据，一站掌握</span><span><CheckOutlined/> AI 助手，随时在侧</span></div></div><div className="login-copyright">© {new Date().getFullYear()} 云迹科技 · 智能经营管理平台</div></section><section className="login-form-area"><div className="login-form"><span className="login-badge">创业团队的轻量经营工作台</span><h2>欢迎来到云迹</h2><p>今天，也让生意更进一步。</p><Form layout="vertical" onFinish={login} initialValues={{account:'demo@yunji.tech',password:'yunji2026',remember:true}} requiredMark={false}><Form.Item name="account" label="账号" rules={[{required:true,message:'请输入演示账号'},{validator:(_,v)=>v==='demo@yunji.tech'?Promise.resolve():Promise.reject(new Error('请使用演示账号 demo@yunji.tech'))}]}><Input size="large" prefix={<UserOutlined/>} placeholder="请输入账号"/></Form.Item><Form.Item name="password" label="密码" rules={[{required:true,message:'请输入演示密码'},{validator:(_,v)=>v==='yunji2026'?Promise.resolve():Promise.reject(new Error('演示密码为 yunji2026'))}]}><Input.Password size="large" prefix={<LockOutlined/>} placeholder="请输入密码"/></Form.Item><div className="login-options"><span><CheckOutlined/> 本机保留登录状态</span><span>本地演示空间</span></div><Button type="primary" size="large" htmlType="submit" block loading={loading}>登录工作台 <ArrowRightOutlined/></Button></Form><div className="login-divider"><span>快速体验</span></div><Button size="large" block onClick={login}>免登录体验演示 <ArrowRightOutlined/></Button><div className="demo-notice"><strong>演示账号已填入，可直接登录</strong><span>所有业务数据仅保存在当前浏览器。<br/>演示账号用于体验，不提供真实身份认证。</span></div></div><div className="login-form-footer">专为一人公司、个体经营者和微型团队打造</div></section></main>;
}
