import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Avatar, Button, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Table, Tag, Tooltip, App as AntApp } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { DeleteOutlined, DownloadOutlined, EditOutlined, PlusOutlined, SearchOutlined, TeamOutlined, FileTextOutlined, InboxOutlined, WalletOutlined, LinkOutlined } from '@ant-design/icons';
import { useStore } from '../store';
import { ledger, money, outstanding, today, total, round } from '../lib/business';
import { PageHeading } from '../components/Shared';
import { statusColors } from './Dashboard';
import type { Customer, Entity, EntityKey, Order, Product, Transaction } from '../types';

const config={customers:{title:'客户管理',desc:'把每一次连接，变成长久的合作。',singular:'客户',icon:<TeamOutlined/>,placeholder:'搜索客户名称、联系人、手机号'},orders:{title:'订单管理',desc:'从合作意向到项目交付，每一笔业务都清晰可见。',singular:'订单',icon:<FileTextOutlined/>,placeholder:'搜索订单编号、名称、客户'},products:{title:'库存管理',desc:'掌握每一件商品，让备货恰到好处。',singular:'商品',icon:<InboxOutlined/>,placeholder:'搜索商品名称、SKU'},transactions:{title:'收支管理',desc:'记好每一笔收支，让现金流心中有数。',singular:'收支',icon:<WalletOutlined/>,placeholder:'搜索收支名称、分类'}};
const required=[{required:true,whitespace:true,message:'请填写此项'}];
const recordedDate=[...required,{validator:(_:unknown,v:string)=>!v||v<=today()?Promise.resolve():Promise.reject(new Error('记录日期不能晚于今天'))}];
const categories=['设计服务','技术服务','运营服务','商品销售','咨询服务','其他收入'];
const options=(values:string[])=>values.map(value=>({label:value,value}));
function downloadCsv(rows:Entity[],name:string){const keys=Object.keys(rows[0]||{});if(!keys.length){return;}const escape=(v:unknown)=>`"${String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')}"`;const text=[keys.join(','),...rows.map(row=>keys.map(k=>escape((row as unknown as Record<string,unknown>)[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`云迹科技-${name}-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function Records({kind}:{kind:EntityKey}) {
  const {message}=AntApp.useApp(); const {data,save,remove}=useStore(); const meta=config[kind]; const navigate=useNavigate();const [params,setParams]=useSearchParams();
  const [search,setSearch]=useState('');const [filter,setFilter]=useState(params.get('filter')||'all');const [category,setCategory]=useState('all');const [page,setPage]=useState(1);
  const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Entity|null>(null);const [form]=Form.useForm();
  const entries=useMemo(()=>kind==='transactions'?ledger(data):data[kind],[data,kind]);
  const categoryList=Array.from(new Set(entries.map(x=>'category' in x?x.category:'industry' in x?x.industry:''))).filter(Boolean);
  function openEditor(row?:Entity){setEditing(row||null);form.resetFields();form.setFieldsValue(row||{date:today(),dueDate:today(),level:'普通客户',industry:'专业服务',status:'待确认',category:kind==='products'?'文创周边':kind==='orders'?'设计服务':'其他收入',type:'收入',amount:0,paidAmount:0,stock:0,threshold:10,price:0,cost:0,unit:'个',notes:'',email:''});setOpen(true);}
  useEffect(()=>{if(params.get('new')==='1'){openEditor();setParams({}, {replace:true});}setFilter(params.get('filter')||'all');},[params]);
  useEffect(()=>{setPage(1);},[search,filter,category]);
  const filtered=entries.filter(row=>{
    const customer='customerId' in row?data.customers.find(c=>c.id===row.customerId)?.name||'':'';
    const haystack=Object.values(row).join(' ')+customer;
    const passCategory=category==='all'||('category' in row?row.category: 'industry' in row?row.industry:'')===category;
    let passFilter=filter==='all';
    if(kind==='customers')passFilter=passFilter||('level' in row&&row.level===filter);
    if(kind==='orders'&&'paidAmount' in row)passFilter=passFilter||(filter==='unpaid'?outstanding(row)>0:row.status===filter);
    if(kind==='products'&&'stock' in row)passFilter=passFilter||(filter==='low'?row.stock<=row.threshold:filter==='normal'&&row.stock>row.threshold);
    if(kind==='transactions'&&'type' in row)passFilter=passFilter||row.type===filter;
    return haystack.toLowerCase().includes(search.trim().toLowerCase())&&passCategory&&passFilter;
  });
  async function onSave(){try{const values=await form.validateFields();const value={...values,id:editing?.id||`${{customers:'CUS',orders:'YJ',products:'PRD',transactions:'FIN'}[kind]}-${Date.now().toString(36).toUpperCase()}`,notes:values.notes||''};Object.keys(value).forEach(k=>{if(typeof value[k]==='string')value[k]=value[k].trim();});if(kind==='customers')value.email=value.email||'';if(kind==='orders'){value.amount=round(value.amount);value.paidAmount=round(value.paidAmount);}save(kind,value as Entity);message.success(`${meta.singular}${editing?'已更新':'已创建'}，数据已保存`);setOpen(false);}catch(e){if(e instanceof Error)message.error(e.message);}}
  function onDelete(row:Entity){try{remove(kind,row.id);message.success('记录已删除');if(filtered.length%8===1&&page>1)setPage(page-1);}catch(e){message.error((e as Error).message);}}
  const actions={title:'操作',key:'actions',width:112,fixed:'right' as const,render:(_:unknown,row:Entity)=>'orderId' in row&&row.orderId?<Tooltip title="回款随订单同步，请在订单中修改"><Button type="link" size="small" icon={<LinkOutlined/>} onClick={()=>navigate(`/orders?search=${row.orderId}`)}>订单</Button></Tooltip>:<Space size={4}><Button aria-label={`编辑${'name' in row?row.name:row.title}`} icon={<EditOutlined/>} size="small" type="text" onClick={()=>openEditor(row)}/><Popconfirm title="确定删除这条记录？" description={kind==='orders'?'删除后对应回款会同步移除。':'删除后无法撤销，请确认。'} onConfirm={()=>onDelete(row)} okText="确认删除" cancelText="取消"><Button aria-label={`删除${'name' in row?row.name:row.title}`} icon={<DeleteOutlined/>} size="small" type="text" danger/></Popconfirm></Space>};
  useEffect(()=>{setSearch(params.get('search')||'');},[params]);
  const columns:ColumnsType<Entity>=kind==='customers'?[
    {title:'客户名称',key:'name',width:240,render:(_,r)=>{const c=r as Customer;return <div className="customer-cell"><Avatar shape="square" style={{background:'#eaf1ff',color:'#3973dd'}}>{c.name.slice(0,1)}</Avatar><div><span className="table-primary">{c.name}</span><span className="table-secondary">{c.id}</span></div></div>;}},
    {title:'联系人',dataIndex:'contact',width:110},{title:'联系方式',dataIndex:'phone',width:155},{title:'行业',dataIndex:'industry',width:110},{title:'客户分级',dataIndex:'level',width:110,render:v=><Tag color={statusColors[v]}>{v}</Tag>},{title:'累计订单额',key:'value',width:140,render:(_,r)=>money(total(data.orders.filter(o=>o.customerId===r.id&&o.status!=='已取消').map(o=>o.amount)))},{title:'创建日期',dataIndex:'date',width:120},actions
  ]:kind==='orders'?[
    {title:'订单信息',key:'order',width:220,render:(_,r)=><div><span className="table-primary">{(r as Order).title}</span><span className="table-secondary">{r.id}</span></div>},{title:'客户',key:'customer',width:180,render:(_,r)=>data.customers.find(c=>c.id===(r as Order).customerId)?.name||'—'},
    {title:'订单金额',dataIndex:'amount',width:135,render:money},{title:'待回款',key:'unpaid',width:135,render:(_,r)=>{const n=outstanding(r as Order);return <span className={n?'amount-warning':'muted'}>{money(n)}</span>;}},{title:'订单状态',dataIndex:'status',width:110,render:v=><Tag color={statusColors[v]}>{v}</Tag>},{title:'订单日期',dataIndex:'date',width:120},actions
  ]:kind==='products'?[
    {title:'商品信息',key:'product',width:245,render:(_,r)=><div className="customer-cell"><span className="product-icon"><InboxOutlined/></span><div><span className="table-primary">{(r as Product).name}</span><span className="table-secondary">{(r as Product).sku}</span></div></div>},{title:'分类',dataIndex:'category',width:120},{title:'当前库存',key:'stock',width:120,render:(_,r)=>{const p=r as Product;return <strong className={p.stock<=p.threshold?'amount-warning':''}>{p.stock} <small className="muted">{p.unit}</small></strong>;}},{title:'安全库存',dataIndex:'threshold',width:110},{title:'销售单价',dataIndex:'price',width:125,render:money},{title:'库存状态',key:'status',width:120,render:(_,r)=>{const p=r as Product;return <Tag color={p.stock===0?'red':p.stock<=p.threshold?'orange':'green'}>{p.stock===0?'缺货':p.stock<=p.threshold?'库存偏低':'库存充足'}</Tag>;}},actions
  ]:[
    {title:'收支事项',key:'transaction',width:290,render:(_,r)=><div><span className="table-primary">{(r as Transaction).title}</span><span className="table-secondary">{'orderId' in r&&r.orderId?'订单自动回款':'手动记账'} · {r.id}</span></div>},{title:'类型',dataIndex:'type',width:100,render:v=><Tag color={v==='收入'?'green':'default'}>{v}</Tag>},{title:'分类',dataIndex:'category',width:130},{title:'金额',key:'amount',width:140,render:(_,r)=><strong className={(r as Transaction).type==='收入'?'positive':'text-dark'}>{(r as Transaction).type==='收入'?'+':'−'} {money((r as Transaction).amount)}</strong>},{title:'日期',dataIndex:'date',width:120},actions
  ];
  const filterOptions=kind==='customers'?options(['重点客户','普通客户','潜在客户']):kind==='orders'?[...options(['待确认','进行中','已完成','已取消']),{label:'未回款',value:'unpaid'}]:kind==='products'?[{label:'库存预警',value:'low'},{label:'库存充足',value:'normal'}]:options(['收入','支出']);
  const stats=kind==='customers'?[['客户总数',data.customers.length+' 位'],['重点客户',data.customers.filter(c=>c.level==='重点客户').length+' 位'],['合作订单',data.orders.filter(o=>o.status!=='已取消').length+' 笔']]:kind==='orders'?[['订单总额',money(total(data.orders.filter(o=>o.status!=='已取消').map(o=>o.amount)))],['累计已回款',money(total(data.orders.filter(o=>o.status!=='已取消').map(o=>o.paidAmount)))],['待回款金额',money(total(data.orders.map(outstanding)))]]:kind==='products'?[['在库商品',data.products.length+' 种'],['库存成本',money(total(data.products.map(p=>p.stock*p.cost)))],['库存预警',data.products.filter(p=>p.stock<=p.threshold).length+' 项']]:[['累计收入',money(total(ledger(data).filter(t=>t.type==='收入').map(t=>t.amount)))],['累计支出',money(total(data.transactions.filter(t=>t.type==='支出').map(t=>t.amount)))],['收支结余',money(total(ledger(data).map(t=>t.type==='收入'?t.amount:-t.amount)))]];
  return <div className="page-enter"><PageHeading title={meta.title} description={meta.desc} extra={<><Button icon={<DownloadOutlined/>} onClick={()=>filtered.length?downloadCsv(filtered,meta.title):message.info('暂无可导出的记录')}>导出记录</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>openEditor()}>新增{meta.singular}</Button></>}/><div className="summary-strip">{stats.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="summary-decoration">{meta.icon}</div></div><section className="panel records-panel"><div className="records-toolbar"><Input prefix={<SearchOutlined/>} aria-label="搜索记录" placeholder={meta.placeholder} value={search} onChange={e=>setSearch(e.target.value)} allowClear/><div className="record-filters"><Select aria-label="状态筛选" value={filter} onChange={setFilter} options={[{label:'全部状态',value:'all'},...filterOptions]}/><Select aria-label="分类筛选" value={category} onChange={setCategory} options={[{label:kind==='customers'?'全部行业':'全部分类',value:'all'},...options(categoryList)]}/><Button type="text" onClick={()=>{setSearch('');setFilter('all');setCategory('all');}}>重置</Button></div></div><Table<Entity> rowKey="id" columns={columns} dataSource={filtered} pagination={{current:page,pageSize:8,showSizeChanger:false,onChange:setPage,showTotal:n=>`共 ${n} 条记录`}} scroll={{x:kind==='customers'?1100:950}} locale={{emptyText:'暂无符合条件的记录，试试调整筛选或新增一条。'}}/><div className="records-note">{kind==='orders'?'已收金额自动计入收支账本；取消订单前请将已收金额改为 0。商品库存独立维护。':kind==='transactions'?'订单回款自动同步，按订单日期入账；请勿重复手动记录。关联回款请在订单中编辑。':kind==='products'?'库存由本页面手动维护；当前版本订单不自动扣减库存。库存等于安全线时即触发预警。':'已关联订单的客户受到删除保护，保留完整业务记录。'}</div></section>
    <Modal title={`${editing?'编辑':'新增'}${meta.singular}`} open={open} onCancel={()=>setOpen(false)} onOk={onSave} okText="保存记录" cancelText="取消" width={600} forceRender><Form form={form} layout="vertical" requiredMark="optional" className="record-form">
      {kind==='customers'?<><Form.Item label="客户名称" name="name" rules={required}><Input placeholder="如：拾光创意工作室" maxLength={60}/></Form.Item><div className="form-two"><Form.Item label="联系人" name="contact" rules={required}><Input maxLength={30}/></Form.Item><Form.Item label="联系电话" name="phone" rules={[{required:true,message:'请输入联系电话'},{pattern:/^[\d+\-\s]{6,20}$/,message:'请输入有效联系电话（6–20 位）'}]}><Input maxLength={20}/></Form.Item></div><Form.Item label="邮箱" name="email" rules={[{type:'email',message:'请输入有效邮箱'}]}><Input placeholder="可选"/></Form.Item><div className="form-two"><Form.Item label="行业" name="industry" rules={required}><Select options={options(['创意设计','生活零售','餐饮服务','专业服务','科技互联网','其他'])}/></Form.Item><Form.Item label="客户分级" name="level" rules={required}><Select options={options(['重点客户','普通客户','潜在客户'])}/></Form.Item></div><Form.Item label="创建日期" name="date" rules={recordedDate}><Input type="date" max={today()}/></Form.Item></>:null}
      {kind==='orders'?<><Form.Item label="订单名称" name="title" rules={required}><Input placeholder="如：品牌视觉设计" maxLength={60}/></Form.Item><Form.Item label="关联客户" name="customerId" rules={required}><Select showSearch optionFilterProp="label" placeholder="选择客户" options={data.customers.map(c=>({label:c.name,value:c.id}))} notFoundContent="请先在客户管理中新增客户"/></Form.Item><div className="form-two"><Form.Item label="业务分类" name="category" rules={required}><Select options={options(categories)}/></Form.Item><Form.Item label="订单状态" name="status" rules={required}><Select options={options(['待确认','进行中','已完成','已取消'])}/></Form.Item></div><div className="form-two"><Form.Item label="订单金额（元）" name="amount" rules={[{required:true,message:'请输入订单金额'},{type:'number',min:0.01,message:'金额需大于 0'}]}><InputNumber min={0.01} max={999999999} precision={2}/></Form.Item><Form.Item label="已收金额（元）" name="paidAmount" dependencies={['amount','status']} rules={[{required:true,message:'请输入已收金额'},({getFieldValue})=>({validator:(_,v)=>v>=0&&v<=getFieldValue('amount')&&(getFieldValue('status')!=='已取消'||v===0)?Promise.resolve():Promise.reject(new Error(getFieldValue('status')==='已取消'?'取消订单的已收金额须为 0':'已收金额不能超过订单金额'))})]}><InputNumber min={0} max={999999999} precision={2}/></Form.Item></div><div className="form-two"><Form.Item label="订单日期" name="date" rules={recordedDate}><Input type="date" max={today()}/></Form.Item><Form.Item label="约定回款日期" name="dueDate" dependencies={['date']} rules={[...required,({getFieldValue})=>({validator:(_,v)=>!v||v>=getFieldValue('date')?Promise.resolve():Promise.reject(new Error('回款日期不能早于订单日期'))})]}><Input type="date"/></Form.Item></div></>:null}
      {kind==='products'?<><Form.Item label="商品名称" name="name" rules={required}><Input maxLength={60}/></Form.Item><div className="form-two"><Form.Item label="SKU 编码" name="sku" rules={required}><Input placeholder="如 YJ-BOX-009" maxLength={40}/></Form.Item><Form.Item label="商品分类" name="category" rules={required}><Select options={options(['文创周边','生活好物','办公用品','印刷物料','其他'])}/></Form.Item></div><div className="form-two"><Form.Item label="当前库存" name="stock" rules={[{required:true,message:'请输入库存'}]}><InputNumber min={0} max={9999999} precision={0}/></Form.Item><Form.Item label="安全库存" name="threshold" rules={[{required:true,message:'请输入预警值'}]}><InputNumber min={0} max={9999999} precision={0}/></Form.Item></div><div className="form-two"><Form.Item label="销售单价（元）" name="price" rules={[{required:true,message:'请输入单价'}]}><InputNumber min={0} max={999999999} precision={2}/></Form.Item><Form.Item label="成本单价（元）" name="cost" rules={[{required:true,message:'请输入成本'}]}><InputNumber min={0} max={999999999} precision={2}/></Form.Item></div><Form.Item label="计量单位" name="unit" rules={required}><Select options={options(['个','套','件','本','箱','台'])}/></Form.Item></>:null}
      {kind==='transactions'?<><Form.Item label="收支事项" name="title" rules={required}><Input placeholder="如：项目咨询收入 / 办公租金" maxLength={60}/></Form.Item><div className="form-two"><Form.Item label="收支类型" name="type" rules={required}><Select options={options(['收入','支出'])}/></Form.Item><Form.Item label="分类" name="category" rules={required}><Select options={options([...categories,'采购成本','场地费用','人力成本','软件服务','营销费用','其他支出'])}/></Form.Item></div><div className="form-two"><Form.Item label="金额（元）" name="amount" rules={[{required:true,message:'请输入金额'},{type:'number',min:0.01,message:'金额需大于 0'}]}><InputNumber min={0.01} max={999999999} precision={2}/></Form.Item><Form.Item label="记账日期" name="date" rules={recordedDate}><Input type="date" max={today()}/></Form.Item></div></>:null}
      <Form.Item label="备注" name="notes"><Input.TextArea rows={2} maxLength={500} showCount placeholder="补充说明（可选）"/></Form.Item></Form></Modal></div>;
}
