import { useState } from 'react';
import { Segmented, Table, Tag } from 'antd';
import { BarChartOutlined, PieChartOutlined, RiseOutlined } from '@ant-design/icons';
import { useStore } from '../store';
import { metrics, money, periodStart, today, total, trend } from '../lib/business';
import { Chart, chartColors, axisStyle } from '../components/Chart';
import { PageHeading, Panel } from '../components/Shared';
import { periodOptions } from './Dashboard';
import type { Period } from '../types';
export default function Statistics(){const {data}=useStore();const [period,setPeriod]=useState<Period>('month');const m=metrics(data,period);const t=trend(data,period);const expenses=Object.entries(m.entries.filter(x=>x.type==='支出').reduce<Record<string,number>>((a,x)=>({...a,[x.category]:(a[x.category]||0)+x.amount}),{})).map(([name,value])=>({name,value}));const ranked=data.customers.map(c=>({...c,amount:total(data.orders.filter(o=>o.customerId===c.id&&o.status!=='已取消'&&o.date>=periodStart(period)&&o.date<=today()).map(o=>o.amount))})).filter(c=>c.amount>0).sort((a,b)=>b.amount-a.amount).slice(0,5);
  return <div className="page-enter"><PageHeading title="数据统计" description="透过数字看经营，让每一次决策都有依据。" extra={<Segmented value={period} options={periodOptions} onChange={v=>setPeriod(v as Period)}/>}/><div className="statistics-kpis"><div><span className="stat-circle"><RiseOutlined/></span><div><span>收支利润率</span><strong>{m.revenue?(m.profit/m.revenue*100).toFixed(1):'0.0'}<small>%</small></strong><small>净利润 / 营业收入</small></div></div><div><span className="stat-circle teal"><BarChartOutlined/></span><div><span>平均订单金额</span><strong>{money(m.orders?total(data.orders.filter(o=>o.status!=='已取消'&&o.date>=periodStart(period)&&o.date<=today()).map(o=>o.amount))/m.orders:0)}</strong><small>有效订单金额 / 订单数</small></div></div><div><span className="stat-circle purple"><PieChartOutlined/></span><div><span>收入支出比</span><strong>{m.expense?(m.revenue/m.expense).toFixed(2):'—'}<small>{m.expense?' : 1':''}</small></strong><small>{m.expense?'每 1 元支出对应的收入':'暂无支出，无法计算比值'}</small></div></div></div><Panel title="经营表现分析" subtitle={period==='week'?'本周每日收支对比':'收入、支出与净利润对比'} extra={<Tag>单位：元</Tag>}><Chart label="收入支出柱状图与净利润折线图" height={330} option={{color:chartColors,tooltip:{trigger:'axis'},legend:{top:8,right:0},grid:{top:55,bottom:10,left:10,right:15,containLabel:true},xAxis:{...axisStyle,type:'category',data:t.map(x=>x.label)},yAxis:{...axisStyle,type:'value'},series:[{name:'收入',type:'bar',barMaxWidth:24,itemStyle:{borderRadius:[4,4,0,0]},data:t.map(x=>x.revenue)},{name:'支出',type:'bar',barMaxWidth:24,itemStyle:{borderRadius:[4,4,0,0]},data:t.map(x=>x.expense)},{name:'净利润',type:'line',smooth:true,data:t.map(x=>x.profit),lineStyle:{width:2},itemStyle:{color:'#8c80ca'}}]}}/></Panel><div className="statistics-bottom"><Panel title="支出结构" subtitle="关注成本的每一个去向"><Chart label="经营支出分类环形图" height={300} option={{color:chartColors,tooltip:{trigger:'item'},legend:{bottom:0,itemWidth:10,textStyle:{color:'#738099'}},series:[{type:'pie',radius:['43%','67%'],center:['50%','43%'],label:{show:false},itemStyle:{borderWidth:4,borderColor:'#fff',borderRadius:6},data:expenses.length?expenses:[{name:'暂无支出',value:1,itemStyle:{color:'#e9edf4'}}]}]}}/></Panel><Panel title="客户贡献排行" subtitle="按所选期间的有效订单金额排序"><Table rowKey="id" dataSource={ranked} pagination={false} columns={[{title:'排名',key:'rank',width:65,render:(_,__,i)=><span className={`rank rank-${i}`}>{String(i+1).padStart(2,'0')}</span>},{title:'客户',dataIndex:'name'},{title:'订单金额',dataIndex:'amount',align:'right',render:money}]} locale={{emptyText:'当前期间暂无客户订单'}}/></Panel></div><div className="records-note">统计口径：收入包含已收订单回款与手动收入；净利润为收支差额。客户贡献按订单金额计算。</div></div>;
}
